export const activities = [
  "ROPE ACCESS",
  "TREE CLIMBING",
  "CONFINED SPACES",
  "TOWERS & INDUSTRIAL STRUCTURES",
  "ROOFS",
  "CONSTRUCTION",
  "ELEVATING PLATFORMS",
  "TEAM RESCUE",
  "TACTICAL",
];

export const productAttributes = [
  "SIT HARNESSES FOR SUSPENSION",
  "FULL BODY HARNESSES",
  "LANYARDS & ENERGY ABSORBERS",
  "CONNECTORS & CARABINERS",
  "ROPE & WEBBING",
  "HELMETS & PROTECTION",
  "ASCENT & DESCENT DEVICES",
];

export const products = [
  // SIT HARNESSES FOR SUSPENSION
  {
    id: 1,
    name: "ACCESS SIT - SIT HARNESS",
    category: "Harnesses",
    subCategory: "SIT HARNESSES FOR SUSPENSION",
    image: "/images/products/access-sit.jpg",
    description: "Professional sit harness designed for rope access work. Features adjustable leg loops and comfortable padding for extended use.",
    features: ["Adjustable leg loops", "Comfort padding", "Multiple gear loops", "Quick-connect buckles"],
    activities: ["ROPE ACCESS", "TOWERS & INDUSTRIAL STRUCTURES", "CONSTRUCTION"],
    price: "$299.00",
    rating: 4.8,
    inStock: true,
    isNew: true,
  },
  {
    id: 2,
    name: "TREE ACCESS EVO - SIT HARNESS",
    category: "Harnesses",
    subCategory: "SIT HARNESSES FOR SUSPENSION",
    image: "/images/products/tree-access-evo.jpg",
    description: "Advanced sit harness for tree climbing professionals. Features lightweight design with reinforced attachment points.",
    features: ["Lightweight design", "Reinforced attachment points", "Breathable mesh padding", "Multiple D-rings"],
    activities: ["TREE CLIMBING", "ROPE ACCESS"],
    price: "$349.00",
    rating: 4.9,
    inStock: true,
    isNew: false,
  },
  {
    id: 3,
    name: "TREE ACCESS ST - SIT HARNESS",
    category: "Harnesses",
    subCategory: "SIT HARNESSES FOR SUSPENSION",
    image: "/images/products/tree-access-st.jpg",
    description: "Specialized sit harness for tree access with enhanced mobility and comfort for long climbs.",
    features: ["Enhanced mobility", "Padded back support", "Adjustable sternum strap", "Tool carrying loops"],
    activities: ["TREE CLIMBING", "TOWERS & INDUSTRIAL STRUCTURES"],
    price: "$399.00",
    rating: 4.7,
    inStock: true,
    isNew: true,
  },
  {
    id: 4,
    name: "GT SIT - SIT HARNESS",
    category: "Harnesses",
    subCategory: "SIT HARNESSES FOR SUSPENSION",
    image: "/images/products/gt-sit.jpg",
    description: "Heavy-duty sit harness for industrial and rescue applications with superior durability.",
    features: ["Heavy-duty construction", "Industrial grade materials", "Quick-release buckles", "Rescue attachment points"],
    activities: ["TEAM RESCUE", "ROPE ACCESS", "CONFINED SPACES"],
    price: "$449.00",
    rating: 4.6,
    inStock: true,
    isNew: false,
  },
  {
    id: 5,
    name: "LIBERTY BLACK - SIT HARNESS",
    category: "Harnesses",
    subCategory: "SIT HARNESSES FOR SUSPENSION",
    image: "/images/products/liberty-black.jpg",
    description: "Premium sit harness with sleek black design, ideal for professional and recreational use.",
    features: ["Premium build quality", "Sleek design", "Memory foam padding", "Color-coded attachment points"],
    activities: ["ROPE ACCESS", "CONSTRUCTION", "TACTICAL"],
    price: "$379.00",
    rating: 4.9,
    inStock: true,
    isNew: false,
  },

  // FULL BODY HARNESSES
  {
    id: 6,
    name: "PRO-TECH FULL BODY HARNESS",
    category: "Harnesses",
    subCategory: "FULL BODY HARNESSES",
    image: "/images/products/pro-tech-full.jpg",
    description: "Professional full body harness for industrial applications with maximum safety features.",
    features: ["Full body support", "Industry certified", "Adjustable shoulder straps", "Quick-connect system"],
    activities: ["CONSTRUCTION", "ROPE ACCESS", "TOWERS & INDUSTRIAL STRUCTURES"],
    price: "$499.00",
    rating: 4.8,
    inStock: true,
    isNew: true,
  },
  {
    id: 7,
    name: "RESCUE PRO FULL BODY",
    category: "Harnesses",
    subCategory: "FULL BODY HARNESSES",
    image: "/images/products/rescue-pro.jpg",
    description: "Specialized full body harness for rescue operations with extra attachment points.",
    features: ["Multiple attachment points", "Emergency release system", "Padded for comfort", "Rescue certified"],
    activities: ["TEAM RESCUE", "CONFINED SPACES", "ROPE ACCESS"],
    price: "$599.00",
    rating: 4.9,
    inStock: true,
    isNew: false,
  },

  // LANYARDS & ENERGY ABSORBERS
  {
    id: 8,
    name: "PROFESSIONAL LANYARD",
    category: "Lanyards",
    subCategory: "LANYARDS & ENERGY ABSORBERS",
    image: "/images/products/pro-lanyard.jpg",
    description: "High-performance lanyard with energy absorber for fall protection systems.",
    features: ["Energy absorbing", "Quick-connect", "Lightweight", "Industrial grade"],
    activities: ["CONSTRUCTION", "ROPE ACCESS", "TOWERS & INDUSTRIAL STRUCTURES"],
    price: "$149.00",
    rating: 4.5,
    inStock: true,
    isNew: false,
  },
  {
    id: 9,
    name: "ADJUSTABLE FALL ARRESTER",
    category: "Lanyards",
    subCategory: "LANYARDS & ENERGY ABSORBERS",
    image: "/images/products/fall-arrester.jpg",
    description: "Adjustable fall arrester with integrated energy absorber for maximum safety.",
    features: ["Adjustable length", "Integrated energy absorber", "Heavy-duty", "CE certified"],
    activities: ["ROOFS", "CONSTRUCTION", "TOWERS & INDUSTRIAL STRUCTURES"],
    price: "$199.00",
    rating: 4.6,
    inStock: true,
    isNew: true,
  },

  // CONNECTORS & CARABINERS
  {
    id: 10,
    name: "STEEL CARABINER SET",
    category: "Connectors",
    subCategory: "CONNECTORS & CARABINERS",
    image: "/images/products/steel-carabiner.jpg",
    description: "Premium steel carabiner set for professional use. Includes locking mechanism for safety.",
    features: ["Steel construction", "Auto-locking", "Corrosion resistant", "Industrial strength"],
    activities: ["ROPE ACCESS", "CONSTRUCTION", "TACTICAL"],
    price: "$89.00",
    rating: 4.7,
    inStock: true,
    isNew: false,
  },
  {
    id: 11,
    name: "ALUMINUM QUICK LINK",
    category: "Connectors",
    subCategory: "CONNECTORS & CARABINERS",
    image: "/images/products/aluminum-quick.jpg",
    description: "Lightweight aluminum quick link for fast and secure connections.",
    features: ["Aluminum construction", "Quick link design", "Lightweight", "Secure locking"],
    activities: ["TREE CLIMBING", "ROPE ACCESS", "TEAM RESCUE"],
    price: "$69.00",
    rating: 4.4,
    inStock: true,
    isNew: false,
  },

  // ROPE & WEBBING
  {
    id: 12,
    name: "STATIC ROPE 11MM",
    category: "Rope",
    subCategory: "ROPE & WEBBING",
    image: "/images/products/static-rope.jpg",
    description: "High-quality static rope for professional access and rescue operations.",
    features: ["11mm diameter", "Static design", "High tensile strength", "Low stretch"],
    activities: ["ROPE ACCESS", "TEAM RESCUE", "CONFINED SPACES"],
    price: "$299.00",
    rating: 4.8,
    inStock: true,
    isNew: true,
  },
  {
    id: 13,
    name: "DYNAMIC ROPE 10.5MM",
    category: "Rope",
    subCategory: "ROPE & WEBBING",
    image: "/images/products/dynamic-rope.jpg",
    description: "Dynamic rope designed for fall protection and dynamic applications.",
    features: ["10.5mm diameter", "Dynamic design", "Impact absorbing", "UIAA certified"],
    activities: ["TREE CLIMBING", "ROPE ACCESS", "CONSTRUCTION"],
    price: "$349.00",
    rating: 4.7,
    inStock: true,
    isNew: false,
  },

  // HELMETS & PROTECTION
  {
    id: 14,
    name: "PROTECTIVE HELMET",
    category: "Helmets",
    subCategory: "HELMETS & PROTECTION",
    image: "/images/products/protective-helmet.jpg",
    description: "Industrial grade protective helmet with adjustable fit and ventilation.",
    features: ["Impact resistant", "Adjustable fit", "Ventilation", "Accessory slots"],
    activities: ["CONSTRUCTION", "ROPE ACCESS", "TOWERS & INDUSTRIAL STRUCTURES"],
    price: "$129.00",
    rating: 4.5,
    inStock: true,
    isNew: false,
  },
  {
    id: 15,
    name: "CLIMBING HELMET",
    category: "Helmets",
    subCategory: "HELMETS & PROTECTION",
    image: "/images/products/climbing-helmet.jpg",
    description: "Lightweight climbing helmet for tree climbing and recreational use.",
    features: ["Lightweight", "Breathable", "Adjustable", "EN certified"],
    activities: ["TREE CLIMBING", "ROPE ACCESS"],
    price: "$159.00",
    rating: 4.6,
    inStock: true,
    isNew: true,
  },

  // ASCENT & DESCENT DEVICES
  {
    id: 16,
    name: "PROFESSIONAL DESCENDER",
    category: "Devices",
    subCategory: "ASCENT & DESCENT DEVICES",
    image: "/images/products/pro-descender.jpg",
    description: "Professional descender for controlled descent in rope access operations.",
    features: ["Controlled descent", "Anti-panic function", "Versatile use", "Heavy-duty"],
    activities: ["ROPE ACCESS", "TEAM RESCUE", "CONSTRUCTION"],
    price: "$249.00",
    rating: 4.8,
    inStock: true,
    isNew: false,
  },
  {
    id: 17,
    name: "ASCENT DEVICE PRO",
    category: "Devices",
    subCategory: "ASCENT & DESCENT DEVICES",
    image: "/images/products/ascent-pro.jpg",
    description: "Professional ascent device for efficient climbing in rope access systems.",
    features: ["Efficient climbing", "Progress capture", "Ergonomic handle", "Industrial grade"],
    activities: ["ROPE ACCESS", "TREE CLIMBING", "TEAM RESCUE"],
    price: "$279.00",
    rating: 4.7,
    inStock: true,
    isNew: true,
  },
];

// Helper function to get product by ID
export const getProductById = (id) => {
  return products.find(product => product.id === id);
};

// Helper function to get products by activity
export const getProductsByActivity = (activity) => {
  return products.filter(product => product.activities.includes(activity));
};

// Helper function to get products by subCategory
export const getProductsBySubCategory = (subCategory) => {
  return products.filter(product => product.subCategory === subCategory);
};